### ISSUE TITLE
JavaScript adware

### ISSUE THREAD

**Issue by claudiob** [alfo/alexforey.com#1]
Hello Alex and congratulations on your amazing work!

Recently I noticed that the home-page of your site redirects to a malware site: jqueryapi.info
This attack has been described in http://www.fuzzysecurity.com/tutorials/17.html
Luckily, that website is no longer active. However, you might want to clean up the content of your js/libs.js file. It was probably obfuscated with a corrupted obfuscator.

My suggestion is to use the pristine JavaScript libraries that you need (such as jQuery).
Thanks and keep up the good work!

**Comment by alfo** [comment]
Thanks, I looked into this and it turned out to be the code I used to obfuscate my email address on the home page. Hopefully this should be fully gone now!
